name    'torian-resolvconf'
version '0.0.1'
source 'https://github.com/torian/puppet-resolvconf'
author 'Emiliano Castagnari ecastag@gmail.com (aka Torian)'
license 'GPL v2'
summary 'resolv.conf module for Puppet.'
description 'Manage resolv.conf file via Puppet'
project_page 'https://github.com/torian/puppet-resolvconf'
